In [1]:
 import numpy as np

In [14]:
a=np.array([2,4,2,4],dtype='int16')
print(a)

[2 4 2 4]


In [5]:
b=np.array([[2,4],[4,2]])
print(b)

[[2 4]
 [4 2]]


In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(4,)

In [9]:
b.shape

(2, 2)

In [12]:
a.dtype

dtype('int16')

In [15]:
a.itemsize

2

In [16]:
a.nbytes

8

accessing

In [36]:
a=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [18]:
a[1,4] 

13

In [20]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a[1,4]

13

In [26]:
# startindex:endindex:stepsize
a[0,1:-1:1]

array([2, 3, 4, 5, 6, 7])

In [37]:
a[1,4]=24
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 24 14 15 16]]


In [40]:
a[:,4]=4
print(a)
a[:,4]=[2,4]
print(a)

[[ 1  2  3  4  4  6  7  8]
 [ 9 10 11 12  4 14 15 16]]
[[ 1  2  3  4  2  6  7  8]
 [ 9 10 11 12  4 14 15 16]]


In [42]:
b=np.array([[[2,4],[4,2]],[[4,2],[2,4]]])
print(b)

[[[2 4]
  [4 2]]

 [[4 2]
  [2 4]]]


In [43]:
b[1,1]

array([2, 4])

In [44]:
b[1,1,1]

4

In [46]:
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[2 4]
  [9 9]]

 [[4 2]
  [8 8]]]


initializing different array types

In [51]:
np.zeros((2))


array([0., 0.])

In [52]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.zeros((2,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [55]:
np.zeros((2,4,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [56]:
np.ones((4,2,2),dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [58]:
np.full((2,4),42,dtype='float16')

array([[42., 42., 42., 42.],
       [42., 42., 42., 42.]], dtype=float16)

In [59]:
a=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [62]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4]])

In [65]:
np.random.rand(4,2)

array([[0.12557478, 0.6370868 ],
       [0.28290491, 0.67131167],
       [0.25465655, 0.5625492 ],
       [0.49555964, 0.41795771]])

In [66]:
np.random.rand(4,2,2)

array([[[0.81303711, 0.78007357],
        [0.67679073, 0.97927444]],

       [[0.01835226, 0.72029119],
        [0.03678497, 0.56174806]],

       [[0.28475167, 0.89718191],
        [0.61389662, 0.5501181 ]],

       [[0.18122054, 0.07393195],
        [0.85901808, 0.1798382 ]]])

In [67]:
np.random.randint(7,size=(2,4))

array([[6, 5, 4, 4],
       [6, 1, 0, 1]])

In [68]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
output=np.ones((4,4))
p=np.zeros((2,2))
p[:,:]=4

output[1:-1,1:-1]=p
print(output)

[[1. 1. 1. 1.]
 [1. 4. 4. 1.]
 [1. 4. 4. 1.]
 [1. 1. 1. 1.]]


In [86]:
a=np.array([1,2,4])
b=a
b[0]=100
print(a)

[100   2   4]


In [87]:
 a=np.array([1,2,4])
b=a.copy()
b[0]=100
print(a)

[1 2 4]


In [89]:
 a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [90]:
a+4

array([5, 6, 7, 8])

In [91]:
a-4

array([-3, -2, -1,  0])

In [92]:
a*4

array([ 4,  8, 12, 16])

In [93]:
a/4

array([0.25, 0.5 , 0.75, 1.  ])

In [94]:
a**4

array([  1,  16,  81, 256], dtype=int32)

In [95]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [96]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [98]:
a=np.ones((2,4))
print(a)
b=np.full((4,2),4)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]
 [4 4]]


array([[16., 16.],
       [16., 16.]])

In [99]:
# find determinant
d=np.identity(4)
np.linalg.det(d)

1.0

In [141]:
output=np.array([[8,24,4],[4,2,4]])
output

array([[ 8, 24,  4],
       [ 4,  2,  4]])

In [112]:
np.min(output)

4

In [113]:
np.max(output)

24

In [116]:
np.min(output,axis=1)

array([4, 2])

In [117]:
np.max(output,axis=1)

array([24,  4])

In [132]:
np.sum(output)

52

In [139]:
np.sum(output,axis=0)

array([12, 28,  8])

In [142]:
np.sum(output,axis=1)

array([36, 10])

In [149]:
numbers=np.array([[2,4,2,4],[4,2,4,2]])
print(numbers)
secondnumbers=numbers.reshape((4,2))
print(secondnumbers)

[[2 4 2 4]
 [4 2 4 2]]
[[2 4]
 [2 4]
 [4 2]
 [4 2]]


In [157]:
# horizontal stack
h1=np.ones((2,4))
print(h1)
h2=np.zeros((2,4))
print(h2)
np.hstack((h1,h2))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [158]:
# data as input text
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [159]:
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [161]:
# advanced indexing
filedata> 52

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [162]:
# values at which filedata is greater than 52
filedata[filedata>52]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [165]:
a=np.array([1,2,4,8,2,4,2,8,4])
a[1]

2

In [166]:
a[2]

4

In [167]:
a[4]

2

In [168]:
a[8]

4

In [169]:
a[[1,2,4,8]]

array([2, 4, 2, 4])

In [170]:
np.any(filedata>52,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [171]:
((filedata>52) & (filedata<125))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [173]:
(~(filedata>52) & (filedata<125))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])